    db.driverClass=org.mariadb.jdbc.Driver
    db.connectionURL=jdbc:mariadb://127.0.0.1:3316/book_manager
    db.userId=boot
    db.password=spring

    project.targetDir=src/main/kotlin
    project.targetPackage=jp.ac.it_college.std.s25005.kotlin.book.manager.infrastructure.database
