    name: book-manager

    services:
      db:
        image: mariadb:12.2
        ports:
          - "3316:3306"
        environment:
          MARIADB_ROOT_PASSWORD: foobarhogepiyo
        volumes:
          - type: volume
            source: db-data
            target: /var/lib/mysql

          - type: bind
            source: ./initdb.d
            target: /docker-entrypoint-initdb.d

      redis:
        image: valkey/valkey:9.1-alpine
        ports:
          - "6379:6379"
        volumes:
          - type: volume
            source: session-data
            target: /data

      front:
        image: book-manager-front
        ports:
          - "8081:80"

    volumes:
      db-data:
      session-data:

